### PR TITLE
full synchronise nodes

### PR DESCRIPTION
**Pull request by molnare**
I had some trouble deploying my ear on a WAS Network Deployment because the plugin could not start my application until the node on which it was installed was not synchronised.  I decided to write a small change to the plugin to synchronise all nodes before any attempt is made to start applications.

### CODE REVIEW

**Comment by imv7** [comment]
Can you add a step to clean caches after sync, before start?

reference: http://www-01.ibm.com/support/docview.wss?uid=swg21607887

**Comment by molnare** [comment]
According to the link you posted, it is not a good idea to clear cache while any of the java virtual machines (meaning only WebSphere) are running.  Please look at point 1 under the "Please note" section. 
If the java processes are stopped then Jenkins can't connect through the SOAP port...

**Comment by greg-peters** [comment]
@molnare Can you describe the scenario where this PR is valid? Is this full synch an optional step needed by the plugin for only clustered deployments?

**Comment by molnare** [comment]
Yes, this PR is intended for clustered deployments. 

We have a scenario where we have more than two clusters, and each cluster with more than two members. When we deploy an application to one of the clusters, we need to stop that cluster, remove the old application, install the new one, synchronize the nodes and start the stopped cluster.

If we don't synchronize the cluster, WebSphere won't recognize the newly installed application, and throw an error that the application is not installed, the application won't start. Also the Jenkins plugin will just hang, waiting for the state of the deployment to change, but it will never change. WebSphere's synchronization process is the reason why the websphere-deployer-plugin is not suited for our scenario in it's current state.

**Pull request merged**
